/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'toggleTask' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    'addTask' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'toggleTask' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };